### ISSUE TITLE
TypeError in the random search of integer variables

### ISSUE THREAD

**Issue by JosepFanals** [lbliek/MVRSM#2]
Hi,

I have been testing the MVRSM algorithm for power grids and it works fine. I just encountered one small problem when performing the random search for integer variables. In particular, in L363 of the original code, we now have the following:

`next_x[0:num_int] = np.random.randint(lb[0:num_int], ub[0:num_int] + 1)  # high is exclusive`

However, adding `1` to `ub[0:num_int]` yields a type error: `TypeError: can only concatenate list (not "int") to list`, which is quite self-explanatory. I would suggest changing it to: 

`next_x[0:num_int] = np.random.randint(lb[0:num_int], np.add(ub[0:num_int], [1] * num_int))`,

where the addition could even be computed outside the loop for better performance. What do you think?

**Comment by lbliek** [comment]
Hi,
thank you for your comment. I could not easily reproduce the error but I tested your change and it leads to the same result and it makes sense, so I will update it soon.
